<![CDATA[
$("ul#relpost_img_sum li img").each(function(){$(this).attr("src",$(this).attr("src").replace(/\/s[0-9]+(\-c)?\//,"/w150-h120-c/"))});
// Related Post
$(document).ready(function(){$("#related-posts").each(function(){var e=$(this),t=e.text();!function(e,t,a){$.ajax({url:"/feeds/posts/default/-/"+t+"?alt=json-in-script&max-results="+a,type:"get",dataType:"jsonp",success:function(t){for(var a="",r='<div class="related">',l=0;l<t.feed.entry.length;l++){for(var n=0;n<t.feed.entry[l].link.length;n++)if("alternate"==t.feed.entry[l].link[n].rel){a=t.feed.entry[l].link[n].href;break}var s=t.feed.entry[l].title.$t,i=t.feed.entry[l].content.$t,d=$("<div>").html(i);if(i.indexOf("https://www.youtube.com/embed/")>-1||i.indexOf("https://www.youtube.com/embed/")>-1)var c=t.feed.entry[l].media$thumbnail.url.replace("/default.jpg","/mqdefault.jpg");else c=i.indexOf("<img")>-1?d.find("img:first").attr("src").replace("s72-c","s600"):"https://2.bp.blogspot.com/-4lZ7DCckjkg/WtaPclghMGI/AAAAAAAAN00/4Cais5iSDRwwUyU6jEc7qlCojlg1izsVgCLcBGAs/s1600/noImage.png";r+='<li><div class="related-thumb"><a class="related-img" href="'+a+'" style="background:url('+c+') no-repeat center center;background-size: cover"/></div><h3 class="related-title"><a href="'+a+'">'+s+"</a></h3></li>"}r+="</div>",e.html(r)}})}(e,t,3)})});
// Lazy Load Share
var lazyshare=!1;window.addEventListener("scroll",function(){(0!=document.documentElement.scrollTop&&!1===lazyshare||0!=document.body.scrollTop&&!1===lazyshare)&&(!function(){var e=document.createElement("script");e.type="text/javascript",e.async=!0,e.src="//platform-api.sharethis.com/js/sharethis.js#property=5b61089df3815e0011ed226c&amp;product=inline-share-buttons";var a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(e,a)}(),lazyshare=!0)},!0);
// Comments
function Display_Reply_Form(r){par_id=$(r).attr("id"),par_id=Valid_Par_Id(par_id),html=$(Cur_Cform_Hdr).html(),".comment_form"==Cur_Cform_Hdr?(reset_html='<a href="#origin_cform" onclick="Reset_Comment_Form()" id="resetcomments">Add Comments</a><a name="origin_cform"/>',$(Cur_Cform_Hdr).html(reset_html)):$(Cur_Cform_Hdr).html(""),Cur_Cform_Hdr="#r_f_c"+par_id,$(Cur_Cform_Hdr).html(html),$("#comment-editor").attr("src",Cform_Ins_ParID(par_id))};
//]]>
